apiVersion: v1
kind: PersistentVolumeClaim
#To get the annotations and storageClassname
metadata:
#The volume name
  name: mysqldb-pvc
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: "dobs.csi.digitalocean.com"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage

