---
apiVersion: v1
kind: Namespace

metadata:
  name: nwdb
  labels:
    version: v1

---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nwdb-config
  namespace: nwdb

data:
  MYSQL_ROOT_PASSWORD: changeit

---
apiVersion: v1
kind: Secret

metadata:
  name: nwdb-secret
  namespace: nwdb

data:
  MYSQL_ROOT_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: northwind-db-deploy
  namespace: nwdb
  labels:
    name: northwind
    version: v1

spec:
  #number of pods
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      name: northwinddb
      version: v1
  template:
    #pod template
    metadata:
      name: northwind-db-pod
      labels:
        #app.kubernetes.io/name: nwapp
        #app.kubernetes.io/version: v1
        #app.kubernetes.io/part-of: nwapp
        name: northwinddb
        version: v1
    spec:
      containers:
      - name: northwind-db-container
        image: halfstopper30/mynorthwinddb:v3
        imagePullPolicy: IfNotPresent
        ports:
        - name: db-port
          containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
            #configMapKeyRef:
              #name: nwdb-config
              name: nwdb-secret
              key: MYSQL_ROOT_PASSWORD