apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwapp-deploy
  namespace: northwind
  labels:
    name: nwapp
    version: v1
spec:
#Number of pods
  replicas: 3
  selector: 
    matchLabels:
      name: nwapp
  template:
  #Pod template
    metadata:
      name: nwapp-pod
      labels:
        name: nwapp
        version: v1
    spec:
      containers:
      - name: nwapp-container
        image: halfstopper30/northwindserver:v3
        imagePullPolicy: IfNotPresent
        env: 
        - name: APP_PORT
          value: "3000"
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: nwapp-config
              key: DB_HOST
        ports:
        - name: nwapp-port
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nwapp-svc
  namespace: northwind
  labels:
    name: nwapp-svc
    version: v1
spec:
  type: LoadBalancer
  selector: 
    name: nwapp
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: nwapp-port