apiVersion: v1
kind: Namespace
metadata: 
  name: northwind
  labels: 
    version: v1
---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nwdb-config
  namespace: northwind

data:
  MYSQL_ROOT_PASSWORD: changeit

---

apiVersion: v1
kind: Secret

metadata:
  name: nwdb-secret
  namespace: northwind

data:
  MYSQL_ROOT_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nwapp-config
  namespace: northwind

data:
  DB_HOST: db-svc.northwind.svc.cluster.local

---
